/** @type {import('next').NextConfig} */
const nextConfig = {
	experimental: {
		// optimizePackageImports: [
		// 	'@auth/prisma-adapter',
		// 	'@hookform/resolvers',
		// 	'@next/bundle-analyzer',
		// 	'@prisma/client',
		// 	'@radix-ui/react-avatar',
		// 	'@radix-ui/react-checkbox',
		// 	'@radix-ui/react-dialog',
		// 	'@radix-ui/react-dropdown-menu',
		// 	'@radix-ui/react-hover-card',
		// 	'@radix-ui/react-label',
		// 	'@radix-ui/react-select',
		// 	'@radix-ui/react-slot',
		// 	'@radix-ui/react-switch',
		// 	'@radix-ui/react-tabs',
		// 	'@radix-ui/react-toast',
		// 	'add',
		// 	'axios',
		// 	'bcrypt',
		// 	'bcryptjs',
		// 	'class-variance-authority',
		// 	'clsx',
		// 	'date-fns',
		// 	'framer-motion',
		// 	'input-otp',
		// 	'leaflet',
		// 	'leaflet-defaulticon-compatibility',
		// 	'leaflet-geosearch',
		// 	'@tanstack/eslint-plugin-query',
		// 	'query-string',
		// 	'@tanstack/react-query',
		// 	'next-auth',
		// 	'next-cloudinary',
		// 	'next-themes',
		// 	'react-countup',
		// 	'react-dom',
		// 	'react-hook-form',
		// 	'react-leaflet',
		// 	'react',
		// 	'react-spinners',
		// 	'recharts',
		// 	'resend',
		// 	'shadcn-ui',
		// 	'tailwind-merge',
		// 	'tailwindcss-animate',
		// 	'zustand',
		// 	'uuid',
		// 	'vaul',
		// 	'zod',
		// 	'@types/bcrypt',
		// 	'@types/bcryptjs',
		// 	'@types/leaflet',
		// 	'@types/react-dom',
		// 	'@types/uuid',
		// 	'autoprefixer',
		// 	'eslint',
		// 	'eslint-config-next',
		// 	'postcss',
		// 	'prisma',
		// 	'tailwindcss',
		// 	'typescript',
		// ],
	},
	images: {
		remotePatterns: [
			{
				protocol: 'https',
				hostname: 'res.cloudinary.com',
			},
			{
				protocol: 'https',
				hostname: 'avatars.githubusercontent.com',
			},
			{
				protocol: 'https',
				hostname: 'lh3.googleusercontent.com',
			},
		],
	},
	logging: {
		fetches: {
			fullUrl: true,
		},
	},
};

export default nextConfig;
